services:
  db:
    image: postgres:16
    container_name: clinic-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khomreantvkon!
      POSTGRES_DB: clinicdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

volumes:
  postgres_data: