spring.application.name=aesthetic-clinic-api

#jwt.secret=your-256-bit-secret-key-here-make-it-at-least-32-bytes-long

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5433/clinicdb
spring.datasource.username=postgres
spring.datasource.password=khomreantvkon!

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect